public class Caminhao{
    private String modelo, marca;
    private int eixos;

    public String getModelo(){
        return modelo;
    } 

    public void setModelo(String modelo){
        this.modelo = modelo;
    }

    public String getMarca(){
        return marca;
    }

    public void setMarca(String marca){
        this.marca = marca;
    }

    public int getEixos(){
        return eixos;
    }

    public void setEixos(int eixos){
        this.eixos = eixos;
    }

}